name: 'integrated_financial_analysis'
version: '1.0.0'
config-version: 2

profile: 'integrated_financial_analysis'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"

models:
  integrated_financial_analysis:
    staging:
      +materialized: view
    marts:
      +materialized: table
